### PR TITLE
Change configuration & add sane defaults

### PR DESCRIPTION
**Pull request by pianocomposer321**

### CODE REVIEW

**Comment by Shatur** [comment]
Thank you for working on this!
Has the configuration changed somehow? I have the following error:

```
E5113: Error while calling lua chunk: ...nfig/nvim/pack/plugins/start/yabs.nvim/lua/yabs/init.lua:38: attempt to index local 'args' (a function value)
```

**Comment by pianocomposer321** [comment]
@Shatur Yeah, sorry about that, I should have been clearer. The configuration change quite a bit actually. You can see an example at lua/yabs/defaults/init.lua. Your testing config would translate to this:

```lua
Yabs = require(“yabs”)
Yabs:setup {
    languages = {
        lua = {
            command = “git status”,
            output = “echo”  -- or “terminal”, or “quickfix”, etc.
        }
    }
}
```

**Comment by pianocomposer321** [comment]
Actually, I think the example in defaults/init.lua is flawed. Any time that it says “build” it should be “command”, I believe.

**Comment by Shatur** [comment]
No problem!

I trying the following:

```lua
Yabs = require("yabs")
Yabs:setup {
    languages = {
        lua = {
            command = "git status",
            output = "quickfix"  -- or “terminal”, or “quickfix”, etc.
        }
    }
}
```

But I do not have any output. What I doing wrong?

> Actually, I think the example in defaults/init.lua is flawed. Any time that it says “build” it should be “command”, I believe.

I would even replace `yabs:build()` with `yabs:run()`.

**Comment by pianocomposer321** [comment]
> No problem!
> 
> I trying the following:
> 
> ```lua
> Yabs = require("yabs")
> Yabs:setup {
>     languages = {
>         lua = {
>             command = "git status",
>             output = "quickfix"  -- or “terminal”, or “quickfix”, etc.
>         }
>     }
> }
> ```
> 
> But I do not have any output. What I doing wrong?
> 
> > Actually, I think the example in defaults/init.lua is flawed. Any time that it says “build” it should be “command”, I believe.
> 
> I would even replace `yabs:build()` with `yabs:run()`.

Unfortunately, I am not in a position to test this right now, but I can think of a few things that might be wrong:

Did you try it with `”echo”` as well? `”echo”` prints the message in the command area. `”quickfix”` should send the output to the quickfix list. Did the quickfix list open after you ran `yabs:build()`? If not, did you open it?

If it’s not any of those things, I will take a look when I get a chance.

**Comment by Shatur** [comment]
> Did you try it with ”echo” as well? ”echo” prints the message in the command area. ”quickfix” should send the output to the quickfix list. Did the quickfix list open after you ran yabs:build()? If not, did you open it

Yes, with any of the options nothing happens. With `quickfix`, quickfix list does not open. If I open it, it’s empty.

**Comment by pianocomposer321** [comment]
> > Did you try it with ”echo” as well? ”echo” prints the message in the command area. ”quickfix” should send the output to the quickfix list. Did the quickfix list open after you ran yabs:build()? If not, did you open it
> 
> Yes, with any of the options nothing happens. With `quickfix`, quickfix list does not open. If I open it, it’s empty.

Sorry, I can’t reproduce this. Here are the exact steps I follow:

1. Open file containing the above code
2. Run `:luaf%`
3. Run `:lua Yabs:build()`

And the quickfix list opens with the output of the `git status` command.

Are these the steps you followed? If not, could you tell me the exact steps to reproduce the issue?

**Comment by Shatur** [comment]
> Are these the steps you followed?

Tried it right now - same result.
I put this code in `init.lua` before.
One note - I do not have Consolidation installed right now. And it works on the master branch.

**Comment by pianocomposer321** [comment]
Can you copy and pasted the output of `:lua print(vim.inspect(require(“yabs”)))` before and after running the test setup?

**Comment by Shatur** [comment]
Oh, sorry, I accidentally switched to the master branch. It works, thanks!

But there is an issue. With `quickfix` output it prints the output only at the end of the program execution. I would expect to see the progress live as it done in Asynctasks.

**Comment by pianocomposer321** [comment]
> Oh, sorry, I accidentally switched to the master branch. It works, thanks!
> 
> But there is an issue. With `quickfix` output it prints the output only at the end of the program execution. I would expect to see the progress live as it done in Asynctasks.

Ok, I think that should be a simple enough fix. I’ll try to work on it today.

**Comment by pianocomposer321** [comment]
Changes pushed.

LMK if this is what you were looking for.

**Comment by Shatur** [comment]
Thanks!
It works, but the quickfix itself only opens automatically at the end. Maybe open it right after `build`?

**Comment by pianocomposer321** [comment]
Hmm, it works for me, although right now it’s opening on the first read. I have it that way because otherwise the quickfix list will open even if there isn’t any output.

**Comment by pianocomposer321** [comment]
To verify it’s working, I made a small script:

```sh
for x in $(seq 5); do
    echo $x
    sleep 1
done
```

For me the quickfix list opens right after it prints “1”.

**Comment by Shatur** [comment]
> I have it that way because otherwise the quickfix list will open even if there isn’t any output.

I would open quickfix right away, because then I can see for sure that I have started a command.

> To verify it’s working, I made a small script:

I tried this script, yes, with it I have a `quickfix` opening right after the first output.
But if I use `cmake --build build/linux-debug` - it opens only at the end. Not sure why...

**Comment by pianocomposer321** [comment]
> > I have it that way because otherwise the quickfix list will open even if there isn’t any output.
> 
> I would open quickfix right away, because then I can see for sure that I have started a command.
> 
> > To verify it’s working, I made a small script:
> 
> I tried this script, yes, with it I have a `quickfix` opening right after the first output.
> But if I use `cmake --build build/linux-debug` - it opens only at the end. Not sure why...

Interesting… I think I’ll make this a config option. Something like `output_types.quickfix.open_on_run`, with possible values being `always`, `never`, and `auto`, with `auto` being the current behavior.

**Comment by Shatur** [comment]
It would be nice!
I think my problem is because the CMake output is overwriting the current line to update the progress.
But the proposed `always` options will solve the issue.

Another suggestion. Maybe print the command being executed for `quickfix`? This is how it works in Asynctaks and it pretty convenient to see what is executing.

**Comment by pianocomposer321** [comment]
Pushed!

The option can be set in `require(“yabs”):setup` either globally in an `output_types` table or per language via an `opts` table. For example:

```lua
require(“yabs”):setup {
    languages = {
        command = “./test.sh”,
        output = “quickfix”,
        opts = {
            open_on_run = “always”
        }
    },
    output_types = {
        quickfix = {
            open_on_run = “auto”  -- Note: auto is the default, you don’t need to set it explicitly here. This is just an example.
        }
    }
}
```

**Comment by pianocomposer321** [comment]
> Another suggestion. Maybe print the command being executed for quickfix? This is how it works in Asynctaks and it pretty convenient to see what is executing.

I assume you mean in the `echo` area?

Anyway, sounds like a nice idea. I’ll probably add it after we get all the wrinkles ironed out with the quickfix output.

**Comment by Shatur** [comment]
> The option can be set in require(“yabs”):setup either globally in an output_types table or per language via an opts table.

Awesome! I like it!

> I assume you mean in the echo area?

No, I meant in quickfix, it allows you to see which command was executed when iterating over quickfixes using `:colder` or `:cnever`.
For now it looks in the following way:

image

What I suggest:

image

**Comment by pianocomposer321** [comment]
Ok, I think I know what needs to be done. But I use a different statusline plugin than you and that message doesn’t show up for me. Could you test this out, because I don’t want to mess up the git history if this isn’t the solution:

In yabs.nvim/lua/yabs/defaults/output/quickfix.lua, line 20, change the line from
```lua
vim.fn.setqflist({}, “ “)
```
to
```lua
vim.fn.setqflist({}, “ “, {title = cmd})
```
and see if that fixes it?

**Comment by Shatur** [comment]
> and see if that fixes it?

Yes!

**Comment by pianocomposer321** [comment]
Perfect!

**Comment by Shatur** [comment]
Could we merge it now?

**Comment by pianocomposer321** [comment]
Unless there is something else you would like to suggest, I think this is ready to be merged.

**Comment by Shatur** [comment]
Looks just awesome to me, thanks!

**Comment by pianocomposer321** [comment]
Thanks for the support!

Now to write the docs. Yay.

**Pull request merged**
