### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by Shatur**
In this PR I added CI checks: 

* Formatting using Stylua. The same formatter will be used in Neovim: https://github.com/neovim/neovim/pull/14987 and already used in most plugins. I used the same style configuration as in Neovim.
* Static analysis using Luacheck. I fixed one warning with it in f5da8615839a21658874ce95c606d84d07f18eb4.

### CODE REVIEW

**Comment by pianocomposer321** [comment]
I've never used CI before in any of my projects, so before I approve this I'd like to make sure I have this straight...

**Comment by Shatur** [comment]
> I've never used CI before in any of my projects, so before I approve this I'd like to make sure I have this straight...

It will show if the checks (formatting and linting) passed for each commit. This will make us more confident in changes and make the code will look consistent.

**Comment by Shatur** [comment]
You can check other popular plugins:

* [bufferline](https://github.com/akinsho/bufferline.nvim/blob/master/.github/workflows/formatting.yaml)
* [Telescope](https://github.com/nvim-telescope/telescope.nvim/blob/master/.github/workflows/lint.yml)
* [packer](https://github.com/wbthomason/packer.nvim/blob/master/.github/workflows/formatting.yaml)

**Comment by pianocomposer321** [comment]
> > I've never used CI before in any of my projects, so before I approve this I'd like to make sure I have this straight...
> 
> 
> 
> It will show if the checks (formatting and linting) passed for each commit. This will make us more confident in changes and make the code will look consistent.

Lol, I didn't mean to actually send that yet.

Also I think it should prevent merge conflicts caused by reformatting later.

Looks good to me!

**Review by pianocomposer321 — APPROVED** [review]

**Comment by Shatur** [comment]
@pianocomposer321 Maybe enable [automatic branch deletion](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches) after merge?

**Pull request merged**
